#!/bin/bash

# Компиляция исходников
# -sourcepath - Зависимые модули из других пакетов
# -classpath - Путь к используемым библиотекам
# -d ./bin - Место, где будут находиться скомпилированные классы

javac -sourcepath ./src -classpath ./lib/logback-core-1.2.6.jar:./lib/logback-classic-1.2.6.jar:./lib/slf4j-api-1.7.32.jar -d bin ./src/edu/csf/oop/java/schedule/Main.java

# Создание jar архива
# --create - Создать архив
# --file - Название архива
# --manifest - Файл манифеста, в котором указана точка входа в программу и путь до скомпилированных файлов и библиотек
# -C - Путь, по которому лежат скомпилированные файлы
# . - Указание на путь, где будет создан архив. . обозначает корневую папку проекта

jar --create --file schedule.jar --manifest manifest.mf -C ./bin/ .
